from __future__ import annotations

import json
from datetime import datetime, timedelta, timezone
from typing import Any

import requests
from typing import TYPE_CHECKING

from app.config import get_settings

if TYPE_CHECKING:
    from sqlalchemy.orm import Session


def format_discord_alert(data: dict[str, Any]) -> str:
    warnings = data.get("warnings") or []
    warning_text = "\n".join(f"- {w}" for w in warnings) if warnings else "- None"
    return f"""🚨 Reality Spread Alert

Market: {data.get("question")}
Action: {data.get("action")}
PPI Score: {data.get("ppi_score")}/100

Polymarket YES: {data.get("polymarket_yes")}
Fair YES: {data.get("fair_yes")}
Premium: {data.get("premium_points")} pts

Emotional side: {data.get("emotional_side")}
Coding: {data.get("ideological_coding")}
Category: {data.get("category")}
Spread: {data.get("spread")}
Depth within 3c: {data.get("depth_3c")}
Resolution risk: {data.get("resolution_risk")}/5

Suggested paper side: {data.get("paper_side") or "NONE"}

Why:
{data.get("why") or "Signal generated by deterministic PPI scoring."}

Warnings:
{warning_text}
""".strip()


def alert_allowed(session: "Session", market_id: int, ppi_score: int) -> bool:
    from sqlalchemy import select
    from app.db.models import Alert

    settings = get_settings()
    cutoff = datetime.now(timezone.utc) - timedelta(hours=settings.alert_cooldown_hours)
    last = session.scalar(
        select(Alert)
        .where(Alert.market_id == market_id, Alert.channel == "discord")
        .order_by(Alert.timestamp.desc())
        .limit(1)
    )
    if last is None:
        return True
    if last.timestamp and last.timestamp < cutoff:
        return True
    try:
        prior_score = int(last.message.split("PPI Score:", 1)[1].split("/100", 1)[0].strip())
    except Exception:
        prior_score = None
    if prior_score is not None and abs(ppi_score - prior_score) >= 10:
        return True
    return False


def send_discord_alert(message: str, webhook_url: str | None = None) -> tuple[bool, str | None]:
    url = webhook_url or get_settings().discord_webhook_url
    if not url:
        return False, "DISCORD_WEBHOOK_URL is not configured"
    try:
        response = requests.post(url, json={"content": message}, timeout=15)
        response.raise_for_status()
        return True, None
    except Exception as exc:
        return False, str(exc)
