from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Runtime configuration loaded from environment variables and .env."""

    app_env: str = "development"
    app_base_url: str = "http://localhost:8501"
    database_url: str = "sqlite:///data/reality_spread.db"

    polymarket_gamma_base_url: str = "https://gamma-api.polymarket.com"
    polymarket_clob_base_url: str = "https://clob.polymarket.com"

    # Evidence sources
    gdelt_enabled: bool = False
    source_timeout_seconds: int = 20
    source_max_retries: int = 3
    source_user_agent: str = "PPIResearch/1.0"
    safe_source_schemes: str = "https"
    allowed_source_domains: str = ""

    # LLM provider abstraction. Values: deterministic, ollama, openai_compatible.
    llm_provider: str = "deterministic"
    llm_base_url: str = "http://localhost:11434"
    llm_model: str = "qwen3:8b"
    llm_api_key: str = ""
    llm_timeout_seconds: int = 90

    # Backward-compatible Ollama names.
    ollama_base_url: str = "http://localhost:11434"
    ollama_model: str = "qwen3:8b"

    # OpenRouter (deepseek/deepseek-v4-flash-0731): a separate, explicitly-versioned comparison
    # model series, never the primary Qwen series. Deliberately not layered on the generic llm_*
    # settings above -- those remain Qwen/Ollama's exclusively, so nothing about the primary
    # series' config path changes by adding this. Pinned model, never an alias or auto-router.
    openrouter_base_url: str = "https://openrouter.ai/api/v1"
    openrouter_api_key: str = ""
    openrouter_model: str = "deepseek/deepseek-v4-flash-0731"
    openrouter_timeout_seconds: int = 90
    openrouter_max_output_tokens: int = 2048

    # Admin authentication. Prefer PPI_ADMIN_PASSWORD_HASH generated by scripts/hash_password.py.
    ppi_admin_username: str = "admin"
    ppi_admin_password_hash: str = ""
    ppi_admin_password: str = ""
    session_secret: str = "change-me-in-production"

    discord_webhook_url: str = ""
    app_stale_hours: int = 30
    # Canonical schedule is 09:00 / 21:00 America/Toronto (see docs/SELF_HOSTED_RUNNER.md),
    # implemented via GitHub Actions' native per-entry `timezone: America/Toronto` schedule field
    # -- GitHub resolves the correct UTC offset for the current DST season on its own. These two
    # settings are independent of that YAML config: they classify a forecast's run_slot from the
    # *actual UTC hour at generation time* (see app.ppi.blind_forecast.determine_run_slot), so
    # they're set to the EDT-equivalent UTC hour, with the +/-2h tolerance absorbing the 1h EST
    # shift (09:00 Toronto = 13:00 UTC in EDT, 14:00 UTC in EST -- both within tolerance of hour
    # 13; 21:00 Toronto = 01:00 UTC in EDT, 02:00 UTC in EST, next UTC calendar day -- both within
    # tolerance of hour 1).
    primary_run_hour_utc: int = 13
    backup_run_hour_utc: int = 1
    scheduler_timezone: str = "America/Toronto"

    # --- Database connectivity resilience (app/db/database.py, app/db/retry.py) --------------
    # Tuned for a twice-daily *batch* workload against the Supabase Supavisor pooler, where a
    # pooled/NAT connection can be reaped while a multi-minute pipeline waits on external LLM
    # calls, or a fresh connect can transiently time out. All have safe defaults; override via
    # env only to tune. Ignored for a sqlite database_url.
    db_connect_timeout_seconds: int = 10          # fail a bad connect fast instead of hanging ~2 min
    db_statement_timeout_ms: int = 60_000         # server-side guard on a hung query; 0 disables
    db_pool_recycle_seconds: int = 280            # < the ~350s idle cull on Supavisor / cloud NAT
    db_pool_size: int = 5
    db_pool_max_overflow: int = 5
    db_pool_timeout_seconds: int = 30
    db_keepalives_idle_seconds: int = 30          # TCP keepalive so an idle-mid-run connection survives
    db_retry_attempts: int = 4                    # 1 try + 3 retries; waits ~1s, 2s, 4s
    db_retry_max_wait_seconds: int = 8
    db_preflight_enabled: bool = True             # SELECT 1 at pipeline start (early detection only)

    # Existing optional integrations retained.
    kalshi_base_url: str = "https://external-api.kalshi.com/trade-api/v2"
    kalshi_api_key: str = ""
    kalshi_api_secret: str = ""
    predictit_marketdata_url: str = "https://www.predictit.org/api/marketdata/all/"
    fec_api_key: str = ""
    votehub_api_key: str = ""
    cook_email: str = ""
    cook_password: str = ""

    # --- PPI Quant v1.5 -------------------------------------------------------------------------
    # The deterministic quantitative election-forecasting engine (app/quant). Shadow mode writes
    # quant_forecasts / ensemble_forecasts rows *without* touching the headline llm_forecasts
    # series, the market snapshots, or the public export -- see scripts/run_quant_shadow.py.
    quant_shadow_enabled: bool = False
    quant_methodology_version: str = "ppi-quant-v1.0"
    ensemble_methodology_version: str = "ppi-ensemble-v1.5"
    # Which series is the public HEADLINE fair value. Stays "legacy_blind_llm" until the v1.5
    # pipeline passes the validation checklist in docs/research/PPI_CUTOVER.md; the flip is then a
    # one-line config change (spec sections 25, 50 Phase E). Values: legacy_blind_llm | quant | ensemble.
    ppi_headline_series: str = "legacy_blind_llm"
    v15_pipeline_enabled: bool = False  # gate the twice-daily v1.5 orchestrator
    # Independent blind-benchmark forecasters -- GPT (spec section 23) + Claude (spec section 24).
    # Separate series, never mixed into the Quant probability. Server-side only; never exposed to
    # the browser. Missing key / SDK -> explicit SKIPPED_PROVIDER row, never a fabricated value.
    openai_api_key: str = ""
    anthropic_api_key: str = ""
    openai_blind_model: str = "gpt-5"  # set to your available frontier OpenAI model
    anthropic_blind_model: str = "claude-opus-5"
    blind_methodology_version: str = "ppi-blind-v1"
    blind_prompt_version: str = "blind_benchmark_v1"
    blind_max_retries: int = 2
    blind_max_web_searches: int = 3
    blind_request_timeout_seconds: int = 120

    # --- Provider / data-acquisition layer (app/providers) -----------------------------------
    provider_timeout_seconds: int = 20
    provider_max_retries: int = 3
    provider_retry_backoff_seconds: float = 1.0
    provider_cache_ttl_minutes: int = 360
    race_match_min_confidence: float = 0.75
    market_classify_min_confidence: float = 0.80

    # --- Decision Desk HQ (the spec's "Decision Labs") ----------------------------------------
    # Polling API: GET /api/v1/polls/generic_ballot and /api/v1/polls/ballot_test. PUBLIC, no
    # auth (verified against polling-api-docs.decisiondeskhq.com, 2026-08).
    decisiondesk_polling_base_url: str = "https://polling.decisiondeskhq.com"
    # Results API v4 (docs.decisiondeskhq.com): historical presidential results -> state partisan
    # lean, via GET /api/v4/race-calls. OAuth2 client-credentials at POST /api/v4/oauth/token --
    # set client id + secret below, or paste a pre-issued static bearer into decisiondesk_api_key.
    # Left disabled (seed CSV fallback) until credentials are provisioned.
    decisiondesk_results_base_url: str = "https://resultsapi.decisiondeskhq.com"
    decisiondesk_client_id: str = ""
    decisiondesk_client_secret: str = ""
    decisiondesk_api_key: str = ""  # optional: a pre-issued static bearer, used instead of OAuth

    # --- VoteHub polls API (public, CC-BY-4.0; verified 2026): generic ballot + race polls -----
    # votehub_api_key is defined above with the legacy adapters; no key is required today, and it
    # is sent as a bearer only if set.
    votehub_api_base_url: str = "https://api.votehub.com"

    # --- PollingSource: a GENERIC secondary poll API (spec section 6). No canonical vendor --
    # point this at any service returning individual poll records as JSON; blank => disabled.
    pollingsource_api_base_url: str = ""
    pollingsource_api_key: str = ""

    # --- OpenFEC: federal candidate identity / incumbency (spec section 8) -------------------
    # Free key at https://api.data.gov/signup/ . Without a key OpenFEC is disabled and candidates
    # come from market discovery + the web fallback only.
    openfec_base_url: str = "https://api.open.fec.gov/v1"

    # --- Polymarket (public, no auth) ------------------------------------------------------
    # polymarket_gamma_base_url / polymarket_clob_base_url are defined above with the legacy config.

    # --- LLM API bases (SDK defaults; override only for a proxy / Azure / gateway) ----------
    openai_base_url: str = ""     # default: https://api.openai.com/v1
    anthropic_base_url: str = ""  # default: https://api.anthropic.com

    scan_interval_minutes: int = 60
    alert_cooldown_hours: int = 6
    min_ppi_alert_score: int = 65
    min_ppi_paper_score: int = 75
    min_premium_for_paper_trade: float = 0.10
    max_allowed_spread: float = 0.04
    min_fair_value_confidence: float = 0.60

    data_dir: Path = Path("data")

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    @property
    def db_path(self) -> Path:
        if self.database_url.startswith("sqlite:///"):
            return Path(self.database_url.replace("sqlite:///", ""))
        return Path("data/reality_spread.db")

    @property
    def source_domain_allowlist(self) -> set[str]:
        return {x.strip().lower() for x in self.allowed_source_domains.split(",") if x.strip()}


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    return Settings()
