from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    """Runtime configuration loaded from environment variables and .env."""

    app_env: str = "development"
    app_base_url: str = "http://localhost:8501"
    database_url: str = "sqlite:///data/reality_spread.db"

    polymarket_gamma_base_url: str = "https://gamma-api.polymarket.com"
    polymarket_clob_base_url: str = "https://clob.polymarket.com"

    # Evidence sources
    gdelt_enabled: bool = False
    source_timeout_seconds: int = 20
    source_max_retries: int = 3
    source_user_agent: str = "PPIResearch/1.0"
    safe_source_schemes: str = "https"
    allowed_source_domains: str = ""

    # LLM provider abstraction. Values: deterministic, ollama, openai_compatible.
    llm_provider: str = "deterministic"
    llm_base_url: str = "http://localhost:11434"
    llm_model: str = "qwen3:8b"
    llm_api_key: str = ""
    llm_timeout_seconds: int = 90

    # Backward-compatible Ollama names.
    ollama_base_url: str = "http://localhost:11434"
    ollama_model: str = "qwen3:8b"

    # Admin authentication. Prefer PPI_ADMIN_PASSWORD_HASH generated by scripts/hash_password.py.
    ppi_admin_username: str = "admin"
    ppi_admin_password_hash: str = ""
    ppi_admin_password: str = ""
    session_secret: str = "change-me-in-production"

    discord_webhook_url: str = ""
    app_stale_hours: int = 30
    # Canonical schedule is 06:00 / 18:00 America/Toronto (see docs/SELF_HOSTED_RUNNER.md). GitHub
    # Actions cron is UTC-only and does not observe DST, so these are the EDT-equivalent UTC hours;
    # the +/-2h tolerance in app.ppi.blind_forecast.determine_run_slot absorbs the 1h EST shift
    # (06:00 Toronto = 10:00 UTC in EDT, 11:00 UTC in EST -- both within tolerance of hour 10).
    primary_run_hour_utc: int = 10
    backup_run_hour_utc: int = 22
    scheduler_timezone: str = "America/Toronto"

    # Existing optional integrations retained.
    kalshi_base_url: str = "https://external-api.kalshi.com/trade-api/v2"
    kalshi_api_key: str = ""
    kalshi_api_secret: str = ""
    predictit_marketdata_url: str = "https://www.predictit.org/api/marketdata/all/"
    fec_api_key: str = ""
    votehub_api_key: str = ""
    cook_email: str = ""
    cook_password: str = ""

    scan_interval_minutes: int = 60
    alert_cooldown_hours: int = 6
    min_ppi_alert_score: int = 65
    min_ppi_paper_score: int = 75
    min_premium_for_paper_trade: float = 0.10
    max_allowed_spread: float = 0.04
    min_fair_value_confidence: float = 0.60

    data_dir: Path = Path("data")

    model_config = SettingsConfigDict(
        env_file=".env",
        env_file_encoding="utf-8",
        extra="ignore",
    )

    @property
    def db_path(self) -> Path:
        if self.database_url.startswith("sqlite:///"):
            return Path(self.database_url.replace("sqlite:///", ""))
        return Path("data/reality_spread.db")

    @property
    def source_domain_allowlist(self) -> set[str]:
        return {x.strip().lower() for x in self.allowed_source_domains.split(",") if x.strip()}


@lru_cache(maxsize=1)
def get_settings() -> Settings:
    return Settings()
