import {
  Archive,
  BarChart3,
  BookCheck,
  BrainCircuit,
  Database,
  Eye,
  FileSearch,
  GitBranch,
  Scale,
  ShieldCheck,
} from "lucide-react";
import { PageHeader } from "../components/PageHeader";

const components = [
  ["Polling", "35%", "Qualifying polls and polling averages, adjusted for recency, methodology and sample quality."],
  ["Forecasts & fundamentals", "25%", "Structural models, candidate quality, incumbency, economic context and electoral fundamentals."],
  ["Comparable markets", "20%", "Related races, chamber-control markets and logically connected contracts used as cross-checks."],
  ["Expert consensus", "10%", "Public assessments from credible forecasters, analysts and subject-matter experts."],
  ["Campaign & news", "10%", "A bounded adjustment for material developments not yet incorporated into slower-moving inputs."],
];

const safeguards = [
  [ShieldCheck, "The model never sees the market price", "The blind forecast is built only from contract text and collected evidence -- market price, bid, ask, spread, volume and liquidity are never shown to it."],
  [Archive, "History is append-only", "A published forecast is never edited in place. Corrections require a new observation, never a rewrite of a prior one."],
  [Eye, "Inputs are visible", "The public can inspect the evidence, rationale, model and prompt version behind every published forecast."],
  [BrainCircuit, "Review can flag, never approve or edit", "A human can flag a forecast for a genuine data-integrity concern, removing it from public display. Nobody can edit a forecast's value or selectively approve one based on its contents."],
];

export function MethodologyPage() {
  return (
    <div className="shell-width page-space methodology-page">
      <PageHeader
        eyebrow="Methodology"
        title="A transparent fair-value process, not a black box."
        description="PPI is designed to make disagreement inspectable: what the market says, what the independent estimate says, why they differ, and how both performed."
      />

      <section className="methodology-hero">
        <div>
          <span className="eyebrow">Core measure</span>
          <h2>Partisan premium</h2>
          <div className="formula-card">
            <span>Market implied probability</span>
            <strong>−</strong>
            <span>PPI fair value</span>
            <strong>=</strong>
            <span>Partisan premium</span>
          </div>
          <p>A positive result means the market is above PPI's independent estimate. A negative result means it is below it. The label describes the gap; it does not prove the cause.</p>
        </div>
        <aside>
          <Scale size={26} />
          <strong>What PPI is testing</strong>
          <p>Whether political prediction markets exhibit persistent, directionally meaningful gaps from a disciplined independent fair-value process—and whether those gaps predict eventual accuracy.</p>
        </aside>
      </section>

      <section className="page-section methodology-section" id="primary-series">
        <div className="section-heading">
          <div className="eyebrow">Primary series</div>
          <h2>The headline PPI fair value is a blind LLM forecast, published automatically.</h2>
          <p>
            A blind model is given the contract text and collected evidence only -- never the market price, bid,
            ask, spread, volume, liquidity, or any other market-derived figure -- and estimates a fair probability
            twice daily. Once that forecast is generated by a scheduled, verified run, it publishes automatically: no
            human approves it, and none is required. A forecast can only be flagged for a genuine data-integrity
            concern, which removes it from display without editing or fabricating anything. If the model abstains,
            that is shown as an explicit abstention, never an invented number.
          </p>
        </div>
      </section>

      <section className="page-section methodology-section" id="components">
        <div className="section-heading">
          <div className="eyebrow">Secondary series (legacy)</div>
          <h2>Five weighted components, human-reviewed before publication.</h2>
          <p>
            An earlier, separate methodology combines five weighted inputs and requires an administrator to approve
            each revision. It is retained for auditability and cross-comparison, but it is no longer the series
            shown as the current headline PPI fair value above.
          </p>
        </div>
        <div className="methodology-components">
          {components.map(([name, weight, description], index) => (
            <article key={name}>
              <div className="methodology-components__number">0{index + 1}</div>
              <div><h3>{name}</h3><p>{description}</p></div>
              <strong>{weight}</strong>
            </article>
          ))}
        </div>
      </section>

      <section className="page-section pipeline-section" id="pipeline">
        <div className="section-heading">
          <div className="eyebrow">Legacy pipeline</div>
          <h2>From raw market data to a human-reviewed revision.</h2>
          <p>This is the secondary, weighted-component series' own pipeline -- distinct from the primary blind-forecast series above, which has no human-review step.</p>
        </div>
        <div className="pipeline-flow">
          {[
            [Database, "Synchronize", "Market metadata, order books, prices, spreads, volume and liquidity."],
            [FileSearch, "Collect evidence", "Approved feeds, official sources, APIs and manually added observations."],
            [BrainCircuit, "Classify", "Relevance, source quality, direction, magnitude and review requirements."],
            [BarChart3, "Construct proposal", "Latest eligible components are combined using configured effective weights."],
            [BookCheck, "Human review", "An administrator verifies inputs, edits the thesis and approves or rejects."],
            [GitBranch, "Publish revision", "The value, evidence and timestamp are appended to immutable public history."],
          ].map(([Icon, title, copy], index) => {
            const TypedIcon = Icon as typeof Database;
            return (
              <article key={title as string}>
                <span className="pipeline-flow__number">{String(index + 1).padStart(2, "0")}</span>
                <span className="pipeline-flow__icon"><TypedIcon size={20} /></span>
                <h3>{title as string}</h3>
                <p>{copy as string}</p>
              </article>
            );
          })}
        </div>
      </section>

      <section className="page-section methodology-section" id="safeguards">
        <div className="section-heading">
          <div className="eyebrow">Editorial safeguards</div>
          <h2>Automation stops before judgment becomes public.</h2>
        </div>
        <div className="safeguard-grid">
          {safeguards.map(([Icon, title, copy]) => {
            const TypedIcon = Icon as typeof ShieldCheck;
            return (
              <article key={title as string}>
                <TypedIcon size={23} />
                <h3>{title as string}</h3>
                <p>{copy as string}</p>
              </article>
            );
          })}
        </div>
      </section>

      <section className="page-section two-column-section two-column-section--balanced">
        <article className="panel prose-block">
          <div className="eyebrow">Observation cadence</div>
          <h2>Twice daily, plus material events</h2>
          <p>The full pipeline runs twice per day. Additional manual runs may follow debates, major polls, candidate withdrawals, court decisions, election results or other events that could materially change the estimate.</p>
          <p>This cadence is designed for a research index, not high-frequency trading. PPI values change when the evidence changes—not merely because the market price moves.</p>
        </article>
        <article className="panel prose-block">
          <div className="eyebrow">Resolution and scoring</div>
          <h2>Predictions remain falsifiable</h2>
          <p>When a market resolves, its initial public PPI probability and the market probability at publication are scored against the binary outcome using Brier scores.</p>
          <p>Lower scores are better. Aggregate comparisons are displayed with explicit sample-size warnings until enough markets have resolved.</p>
        </article>
      </section>

      <section className="page-section limitations-panel">
        <div><div className="eyebrow">Limitations</div><h2>What the index cannot prove</h2></div>
        <div className="limitations-panel__grid">
          <p><strong>Selection effects.</strong> Tracked markets are curated and may not represent every political prediction market.</p>
          <p><strong>Model risk.</strong> PPI fair values depend on component quality, weighting choices and human judgment.</p>
          <p><strong>Causal claims.</strong> A premium can be consistent with partisan enthusiasm without proving that partisanship caused it.</p>
          <p><strong>Small samples.</strong> Early wins or losses should not be treated as strong evidence until many markets resolve.</p>
        </div>
      </section>

      <section className="page-section">
        <article className="panel">
          <div className="panel__header"><div>
            <div className="eyebrow">PPI v1.5 — quantitative rewrite (shadow)</div>
            <h2>From "what probability feels right?" to a margin distribution</h2>
            <p>A second forecasting system runs alongside the headline. It replaces the LLM-decides-the-probability design with an explicit, deterministic election model. It is shown on the <a href="/v15">PPI v1.5</a> page and is not yet the public headline.</p>
          </div></div>
          <ol className="v15-method-list">
            <li><strong>PPI does not know the true probability.</strong> It states an estimate implied by explicit assumptions.</li>
            <li><strong>Quant estimates an expected election margin</strong> in vote-margin space, from polls and fundamentals — never in probability space until the last step.</li>
            <li><strong>Polls and fundamentals are combined.</strong> A weighted polling average (recency, sample, population, pollster grade, sponsor, anti-flooding) is blended with a fundamentals margin (state partisan lean + national environment + incumbency); polling earns more weight with more independent, newer polls and less time to the election.</li>
            <li><strong>Forecast uncertainty converts the margin to a probability</strong> as <code>Φ(μ / σ)</code>, where σ combines time-to-election, sparse-polling, office and candidate-status components. A poll lead is never read as certainty.</li>
            <li><strong>Market information is excluded from the forecast.</strong> The quantitative function has no market-price argument; the market–model spread is computed only after the forecast is stored.</li>
            <li><strong>GPT and Claude are independent blind robustness checks.</strong> Each forecasts from the same timestamp-locked, market-free evidence — no market price, no Quant value, no sight of the other model.</li>
            <li><strong>Ensemble weights are predeclared:</strong> 0.60·Quant + 0.20·GPT + 0.20·Claude. If a component is missing the ensemble is reported unavailable, never silently reweighted.</li>
            <li><strong>History is immutable.</strong> Every forecast is append-only with its methodology version, config hash, input hash and evidence hash. Corrections add a new revision.</li>
            <li><strong>Missing data can cause abstention.</strong> Thin, ambiguous or contradictory inputs yield an explicit abstain rather than invented precision.</li>
            <li><strong>The market–model spread does not prove partisanship.</strong> It is an observation. HIGH robustness (models agree, diverge from the market together) is the only case treated as a candidate anomaly.</li>
            <li><strong>Parameters are versioned and provisional.</strong> The v1.0 constants (21-day poll half-life, incumbency bonuses, uncertainty schedule, pollster-grade weights) are transparent starting points, not backtested optima.</li>
            <li><strong>Every model is judged by resolved outcomes.</strong> When a race resolves, Market, Quant, GPT, Claude and the Ensemble are each scored with a Brier score at standard horizons, using the observation nearest each horizon without lookahead.</li>
          </ol>
        </article>
      </section>
    </div>
  );
}
